version: '2.1'

services:
  proxy:
    privileged: true
    image: dockercloud/haproxy:latest
    ports:
      - 8080:80
    links:
      - grafana
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  db:
    image: postgres:alpine
    volumes:
      - pgdata_grafana:/var/lib/postgresql/data
    ports: 
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: grafana
      POSTGRES_DB: grafana

  grafana:
    depends_on:
      db:
        condition: service_healthy
    image: grafana/grafana
    expose:
      - 3000
    environment:
      GF_SECURITY_ADMIN_PASSWORD: password
      GF_SECURITY_ADMIN_USER: admin
      # GF_SECURITY_LOGIN_REMEMBER_DAYS:
      GF_USERS_ALLOW_ORG_CREATE: "false"
      GF_SERVER_HTTP_PORT: 3000
      # GF_SERVER_HTTP_ADDR: localhost
      GF_DATABASE_TYPE: postgres
      GF_DATABASE_HOST: db
      GF_DATABASE_NAME: grafana
      GF_DATABASE_USER: grafana
      GF_DATABASE_PASSWORD: password
      GF_DATABASE_MAX_IDLE_CONN: 20
      GF_DATABASE_MAX_OPEN_CONN: 20
      GF_SESSION_PROVIDER: memcache
      GF_SESSION_PROVIDER_CONFIG: memcached:11211
      # GF_SESSION_COOKIE_NAME: 
      # GF_SESSION_COOKIE_SECURE:
      # GF_SESSION_SESSION_LIFE_TIME:

  graphite:
    image: hopsoft/graphite-statsd
    ports:
      - 8081:80
      - 2003-2004:2003-2004
      - 2023-2024:2023-2024
      - 8125:8125/udp
      - 8126:8126

  memcached:
    image: memcached:alpine
    expose:
      - 11211

volumes:
  pgdata_grafana:

